# Generated by Django 4.2.3 on 2023-08-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='created_by',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('python', 'Python'), ('vanilla_js', 'Vanilla JS'), ('react', 'React JS'), ('cpp', 'CPP')], max_length=15),
        ),
    ]
