# Generated by Django 4.2.3 on 2023-08-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_directory_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
